### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by andrevalgrande** [xndcn/atom-debugger#11]
[Enter steps to reproduce below:]
1. Go to "toggle debugging"
2. Enter binary path
3. Click "start"
4. Navigate to any file in the project
5. Right click a line and click "toggle breakpoint"

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: [atom-debugger](https://github.com/xndcn/atom-debugger) package, v0.1.5
### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:141

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:266:12)
    at GDB.module.exports.GDB.postCommand (C:\Users\Deco\.atom\packages\atom-debugger\lib\backend\gdb\gdb.coffee:163:14)
    at GDB.module.exports.GDB.insertBreak (C:\Users\Deco\.atom\packages\atom-debugger\lib\backend\gdb\gdb.coffee:125:8)
    at DebuggerView.module.exports.DebuggerView.insertBreak (C:\Users\Deco\.atom\packages\atom-debugger\lib\debugger-view.coffee:137:10)
    at DebuggerView.module.exports.DebuggerView.toggleBreak (C:\Users\Deco\.atom\packages\atom-debugger\lib\debugger-view.coffee:122:8)
    at atom-workspace.<anonymous> (C:\Users\Deco\.atom\packages\atom-debugger\lib\debugger-view.coffee:200:8)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Deco\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Deco\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Deco\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:145:19)
    at [object Object].jQuery.fn.trigger (C:\Users\Deco\AppData\Local\atom\app-1.0.19\resources\app.asar\src\space-pen-extensions.js:64:23)
```
### Commands

```
     -0:40.8.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:39.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.1.0 debugger:toggle (atom-text-editor.editor.is-focused)
     -0:09.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "livereload",
      "file-icons"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-debugger, v0.1.5
emmet, v2.3.13
go-plus, v3.5.1
highlight-selected, v0.10.1
minimap, v4.13.4

# Dev
No dev packages
```

**Comment by xndcn** [comment]
@andrevalgrande I'm sorry but this package may not work on Windows...
