### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by NuclearCookie** [xndcn/atom-debugger#12]
[Enter steps to reproduce below:]
1. Give absolute path to executable
2. Leave checkmark for breakpoint in main
3. Run
4. Continue after breakpoint was hit

**Atom Version**: 1.0.19
**System**: Linux Mint
**Thrown From**: [atom-debugger](https://github.com/xndcn/atom-debugger) package, v0.1.5
### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:8

TypeError: Path must be a string. Received undefined
  at assertPath (path.js:8:11)
  at Object.posix.resolve (path.js:413:5)
  at /home/pieter/.atom/packages/atom-debugger/lib/debugger-view.coffee:237:25
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /home/pieter/.atom/packages/atom-debugger/lib/backend/gdb/gdb.coffee:28:24
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:85:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:520:20)

```
### Commands

```
 14x -1:44 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -1:15.4.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -1:14.6.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -1:12.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:44.4.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -0:43.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:43.1.0 debugger:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -0:42.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:41.4.0 core:undo (atom-text-editor.editor.mini.is-focused)
     -0:29.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:27.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:15.9.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -0:14.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14.7.0 debugger:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -0:14 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:13 core:backspace (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-debugger, v0.1.5
atom-gdb, v0.4.0
build, v0.47.0
file-icons, v1.6.9
language-lua, v0.9.4
project-manager, v2.6.1

# Dev
No dev packages
```

**Comment by NuclearCookie** [comment]
Note: This is probably happening in catching the next error. There's something about an invalid string

**Comment by xndcn** [comment]
@NuclearCookie Sorry for that... I can't reproduce this error... 
Could you insert this code `console.log(frame)` before line #237 in file `lib/debugger-view.coffee`? Then open developer tool and see what would be output in `Console` tab when this error happened. Thank you!
