### ISSUE TITLE
Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments require...

### ISSUE THREAD

**Issue by madhu-anugu** [xndcn/atom-debugger#23]
[Enter steps to reproduce below:]
1. Packages (Toggle debugging) and the following error is thrown

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-debugger](https://github.com/xndcn/atom-debugger) package, v0.1.6
### Stack Trace

Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.

```
At /Users/suddiv/.atom/packages/atom-debugger/lib/debugger-view.coffee:261

TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.
    at TypeError (native)
    at DebuggerView.module.exports.DebuggerView.destroy (/Users/../.atom/packages/atom-debugger/lib/debugger-view.coffee:261:22)
    at Object.module.exports.Debugger.toggle (/Users/../.atom/packages/atom-debugger/lib/debugger.coffee:31:21)
    at atom-workspace.subscriptions.add.atom.commands.add.debugger:toggle (/Users/../.atom/packages/atom-debugger/lib/debugger.coffee:14:83)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/../softwares/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Users/../softwares/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/../softwares/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Users/../softwares/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1127:28)
    at EventEmitter.outerCallback (/Users/../softwares/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:341:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```
### Commands

```
     -6:54 debugger:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -6:24.8.0 gpp-compiler:tree-gdb (span.name.icon.icon-file-text)
     -6:17.6.0 debugger:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:00.8.0 atom-gdb:toggle-breakpoint (atom-text-editor.editor.is-focused)
  2x -4:38.2.0 debugger:toggle (atom-text-editor.editor.is-focused)
     -4:21.4.0 gpp-compiler:tree-compile (span.name.icon.icon-file-text)
     -3:58.3.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -3:51.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:48.4.0 core:move-right (atom-text-editor.editor.is-focused)
  8x -3:46.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:55.1.0 fuzzy-finder:toggle-git-status-finder (atom-text-editor.editor.is-focused)
  2x -1:53.8.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:35.9.0 atom-gdb:select-executable (atom-text-editor.editor.is-focused)
     -1:23.3.0 atom-gdb:start (atom-text-editor.editor.is-focused)
     -0:49.6.0 pane:split-up (span.disable-text)
  2x -0:32.9.0 debugger:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-gdb"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.13 (inactive)
atom-debugger, v0.1.6 (active)
atom-gdb, v0.4.0 (inactive)
atom-live-server, v1.2.5 (inactive)
gpp-compiler, v3.0.7 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by legodude17** [comment]
This happened to me when gdb fails or the target doesn't have debugging symbols, and then when you try to close it.
