### ISSUE TITLE
Uncaught TypeError: Cannot read property 'domNode' of null

### ISSUE THREAD

**Issue by LoLei** [xndcn/atom-debugger#5]
[Enter steps to reproduce below:]
1. Enter path of executable
2. Press Start

![screenshot from 2015-05-21 12 04 43](https://cloud.githubusercontent.com/assets/9076894/7746340/bcca6472-ffb1-11e4-8e6b-1be8be97bd2a.png)

**Atom Version**: 0.200.0
**System**: linux 3.19.0-18-generic
**Thrown From**: [atom-debugger](https://github.com/xndcn/atom-debugger) package, v0.1.2
### Stack Trace

Uncaught TypeError: Cannot read property 'domNode' of null

```
At /home/lo/.atom/packages/atom-debugger/lib/debugger-view.coffee:180

TypeError: Cannot read property 'domNode' of null
  at DebuggerView.module.exports.DebuggerView.hackGutterDblClick (/home/lo/.atom/packages/atom-debugger/lib/debugger-view.coffee:180:11)
  at /home/lo/.atom/packages/atom-debugger/lib/debugger-view.coffee:199:8
  at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:267:9)
  at DebuggerView.module.exports.DebuggerView.handleEvents (/home/lo/.atom/packages/atom-debugger/lib/debugger-view.coffee:193:39)
  at DebuggerView.module.exports.DebuggerView.initialize (/home/lo/.atom/packages/atom-debugger/lib/debugger-view.coffee:35:6)
  at DebuggerView.View (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new DebuggerView (/home/lo/.atom/packages/atom-debugger/lib/debugger-view.coffee:11:3)
  at /home/lo/.atom/packages/atom-debugger/lib/debugger.coffee:36:31
  at HTMLButtonElement.<anonymous> (/home/lo/.atom/packages/atom-debugger/lib/open-dialog-view.coffee:23:7)
  at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -1:05.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -1:03.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:57.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:56.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:56.8.0 application:open-folder (atom-text-editor.editor)
     -0:47.4.0 debugger:toggle (atom-text-editor.editor.is-focused)
  2x -0:43.8.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -0:11.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 core:cancel (button.inline-block.btn)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-debugger, v0.1.2
autocomplete-clang, v0.7.0
linter, v0.12.6
linter-clang, v2.25.1
minimap, v4.9.0

# Dev
No dev packages
```

**Comment by xndcn** [comment]
@LorenzLeitner Sorry about that, `gutterComponent` has been renamed to `gutterContainerComponent`...
Now fixed, please update and check it again, thank you!

**Comment by LoLei** [comment]
Thank you, it works now.

One feature I would really like is a watch and locals window with variable values, but I see that's already on your TODO.

![image](https://cloud.githubusercontent.com/assets/9076894/7771293/98b6f8a8-0096-11e5-83a6-abd8e88f6814.png)
