### ISSUE TITLE
Uncaught TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by yotamN** [xndcn/atom-debugger#8]
```
TypeError: Arguments to path.resolve must be strings
  at Object.posix.resolve (path.js:400:13)
  at /home/yotam/.atom/packages/atom-debugger/lib/debugger-view.coffee:94:25
  at Object.<anonymous> (/home/yotam/.atom/packages/atom-debugger/lib/backend/gdb/gdb.coffee:129:9)
  at /home/yotam/.atom/packages/atom-debugger/lib/backend/gdb/gdb.coffee:33:17
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:85:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)
```

I inserted a path and it's returned this, the path is `/home/yotam/MEGA/Magshimim/C10/test`
I tried to change the file name to have a file type in his name (test.out) and it's still doesn't work.

**Comment by ghost** [comment]
Same here:

**Atom Version**: 1.0.2
**System**: Ubuntu 14.04.2
**Thrown From**: [atom-debugger](https://github.com/xndcn/atom-debugger) package, v0.1.4

### Stack Trace

Uncaught TypeError: Arguments to path.resolve must be strings

```
At path.js:400

TypeError: Arguments to path.resolve must be strings
  at Object.posix.resolve (path.js:400:13)
  at /home/nils/.atom/packages/atom-debugger/lib/debugger-view.coffee:94:25
  at Object.<anonymous> (/home/nils/.atom/packages/atom-debugger/lib/backend/gdb/gdb.coffee:129:9)
  at /home/nils/.atom/packages/atom-debugger/lib/backend/gdb/gdb.coffee:33:17
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:85:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
     -8:42.1.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -8:41.8.0 core:save (atom-text-editor.editor.is-focused)
     -8:00.4.0 window:run-package-specs (atom-text-editor.editor.is-focused)
     -7:55.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  8x -7:53 core:backspace (atom-text-editor.editor.mini.is-focused)
     -7:48.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:48.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -7:31.2.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -6:51.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:51.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -6:50.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:17 debugger:toggle (div.settings-view.pane-item)
     -4:06.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:52.5.0 debugger:toggle (atom-text-editor.editor.is-focused)
     -3:44.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:37.2.0 debugger:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-dark-ui.find-visible)
```

### Config

``` json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-debugger, v0.1.4
debugger, v0.0.1
latex, v0.25.0
texlicious, v0.4.4

# Dev
No dev packages
```

**Comment by linde12** [comment]
Same error here, makes the plugin unusable i'm afraid :(

**Comment by classner** [comment]
Same error...

**Comment by xndcn** [comment]
@linde12 @classner Really sorry for that... You have to insert filename with `full path`, such as `/home/foo/bar`
Please try it again, thank you!

**Comment by linde12** [comment]
@xndcn Thanks for your quick reply! I tried with entering the full path but i'm still getting the same error. I put /home/ocalinde/projects/asdf/go (where "go" is my executable) but i'm still getting the same error. Also tried without the binary name and i get the same result. Am i still doing something wrong maybe?

Thanks again for the quick reply. I think this plugin has great potential and i'd really like to use it!

**Comment by classner** [comment]
I also used the full path to the executable and got the error...

**Comment by yotamN** [comment]
Also used the full path

@xndcn BTW, are you still working on this package?

**Comment by xndcn** [comment]
Sorry, my fault...
I think that's because you compiled without `-g` option, so the executable binary has no information for  debugger...
Anyway, now fixed, please update and try it again, thank you!

**Comment by xndcn** [comment]
@yotamN I'm too busy to working on it these days...  It's very kind of you that you can help to improve this!

**Comment by classner** [comment]
Great, thank you! That was actually causing the problem! :+1: 

It makes sense to not allow debugging without symbols, and with the additional check it will be easier to locate the source of the problem.
