### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toggleBreak' of undefined

### ISSUE THREAD

**Issue by dangwalsh** [xndcn/atom-debugger#9]
[Enter steps to reproduce below:]
1. Run atom-debugger
2. Right-click on line in code, select Toggle Breakpoint

**Atom Version**: 0.211.0-309410f
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-debugger](https://github.com/xndcn/atom-debugger) package, v0.1.3
**User**: root
### Stack Trace

Uncaught TypeError: Cannot read property 'toggleBreak' of undefined

```
At /Users/danielwalsh/.atom/packages/atom-debugger/lib/debugger-view.coffee:194

TypeError: Cannot read property 'toggleBreak' of undefined
  at atom-workspace.subscriptions.add.atom.commands.add.debugger:toggle-breakpoint (/Users/danielwalsh/.atom/packages/atom-debugger/lib/debugger-view.coffee:194:20)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
     -3:10.1.0 debugger:toggle (atom-text-editor.editor.is-focused)
     -3:07.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -1:18.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:48.8.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "steam-pirate-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-debugger, v0.1.3
atom-typescript, v4.5.16
atom-yeoman, v0.3.11
browser-plus, v0.0.23
language-aspx, v0.4.0
linter, v0.12.7
omnisharp-atom, v0.15.1
steam-pirate-ui, v0.5.1

# Dev
No dev packages
```

**Comment by xndcn** [comment]
@dangwalsh Sorry for that, now fixed, please update and check it again, thank you!
